In [3]:
# 1. Implement Data Manipulation (Numpy library) Operations Broadcasting Indexing and slicing. Also display head, tail, size of data and remove null values from the dataset.

In [4]:
# Broadcasting
import numpy as np

#create a numpy array
arr1=np.arange(1,10)
print(arr1)

b=5
result=arr1*b
print(result)

[1 2 3 4 5 6 7 8 9]
[ 5 10 15 20 25 30 35 40 45]


In [5]:
# Indexing

arr2 = np.array([10, 20, 30, 40, 50])

element = arr2[2]  # Accessing the third element
print(element)

30


In [6]:
# Slicing 
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_slice = matrix[1, :]  # Extracting the second row
print(row_slice)

column_slice = matrix[:, 1]  # Extracting the second column
print(column_slice)

submatrix = matrix[0:2, 1:]  # Extracting a submatrix from rows 1 and 2, and columns 2 and 3
print(submatrix)

[4 5 6]
[2 5 8]
[[2 3]
 [5 6]]


In [7]:
# read csv
import pandas as pd

data=pd.read_csv('weight-height.csv')

In [9]:
#head
print(data.head())


             Height            Weight
0   73.847017017515  241.893563180437
1  68.7819040458903  162.310472521300
2  74.1101053917849    212.7408555565
3  71.7309784033377  220.042470303077
4  69.8817958611153  206.349800623871


In [10]:
#tail
print(data.tail())

                Height            Weight
9995  66.1726521477708  136.777454183235
9996   67.067154649054  170.867905890713
9997  63.8679922137577  128.475318784122
9998  69.0342431307346  163.852461346571
9999  61.9442458795172  113.649102675312


In [17]:
#size of data
print(data.size)


20000


In [15]:
# Detecting null values

print(data.isnull().sum()) #gives total null values per column


Height    2
Weight    2
dtype: int64


In [18]:
# Removing null values

df=data.dropna()  #deletes rows with null value
print(df.isnull().sum())

Height    0
Weight    0
dtype: int64


In [19]:
print(data.notnull().sum()) # not null values

Height    9998
Weight    9998
dtype: int64
