In [34]:
import pandas as pd
import numpy as np

data=pd.read_csv('weight-height.csv')
data.head(5)

Height            Weight
0   73.847017017515  241.893563180437
1  68.7819040458903  162.310472521300
2  74.1101053917849    212.7408555565
3  71.7309784033377  220.042470303077
4  69.8817958611153  206.349800623871

In [35]:
# Detecting null values
print(data.isnull().sum()) #gives total null values per column

Height    2
Weight    2
dtype: int64


In [36]:
# Removing null values

df=data.dropna()  #deletes rows with null value
print(df.isnull().sum())

Height    0
Weight    0
dtype: int64


In [37]:
# Creating a DataFrame with null values
data = pd.DataFrame({
    'A': [1, 2, np.nan, 4, 5],
    'B': [6, np.nan, 8, np.nan, 10]
})
print(data)

     A     B
0  1.0   6.0
1  2.0   NaN
2  NaN   8.0
3  4.0   NaN
4  5.0  10.0


In [38]:
# Imputing Null values with mean
imputed_data=data.fillna(data.mean())
print(imputed_data)


     A     B
0  1.0   6.0
1  2.0   8.0
2  3.0   8.0
3  4.0   8.0
4  5.0  10.0


In [39]:
# Imputing Null values with specific value
imputed_data=data.fillna(0)
print(imputed_data)

     A     B
0  1.0   6.0
1  2.0   0.0
2  0.0   8.0
3  4.0   0.0
4  5.0  10.0


In [40]:

# Forward fill
data_ffill = data.fillna(method='ffill')
print(data_ffill)

     A     B
0  1.0   6.0
1  2.0   6.0
2  2.0   8.0
3  4.0   8.0
4  5.0  10.0


In [41]:

# Backward fill
data_bfill = data.fillna(method='bfill')
print(data_bfill)

     A     B
0  1.0   6.0
1  2.0   8.0
2  4.0   8.0
3  4.0  10.0
4  5.0  10.0


In [42]:
# Interpolation

data_interpolated = data.interpolate(method='linear')
print(data_interpolated)

     A     B
0  1.0   6.0
1  2.0   7.0
2  3.0   8.0
3  4.0   9.0
4  5.0  10.0


In [43]:
#numpy tensors

numpy_tensor=data_interpolated.to_numpy()
print(numpy_tensor)

[[ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]
 [ 5. 10.]]


In [44]:
#pytorch tensors
import torch

# Convert DataFrame to PyTorch tensor
torch_tensor = torch.tensor(data_interpolated.values)
print(torch_tensor)

tensor([[ 1.,  6.],
        [ 2.,  7.],
        [ 3.,  8.],
        [ 4.,  9.],
        [ 5., 10.]], dtype=torch.float64)


In [45]:
#tensorflow tensors

import tensorflow as tf

# Convert DataFrame to TensorFlow tensor
tf_tensor = tf.constant(data_interpolated.values)
print(tf_tensor)

tf.Tensor(
[[ 1.  6.]
 [ 2.  7.]
 [ 3.  8.]
 [ 4.  9.]
 [ 5. 10.]], shape=(5, 2), dtype=float64)
