In [1]:
#Implement Forward pass with matrix multiplication 

In [2]:
import numpy as np

def activation(z):
  return 1/(1+np.exp(-z))

def loss_function(target,output):                #Mean Squared Error
  return (1/len(target))*np.square(target-output)

def forwardpass(x,weights,bias):
  weighted_sum=np.dot(x,weights)+bias
  print("Weighted Sum :\n",weighted_sum)
  output=activation(weighted_sum)
  return output

#input data
x=np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

#weights
weights=np.array([[0.8], [0.2]])

#targets
targets=np.array([[1], [0], [1]])

#bias
bias=np.array([0.1])

print("Input Data :\n",x)

output=forwardpass(x,weights,bias)
loss=loss_function(targets,output)

print("Output :\n",output)
print("Loss :\n",loss)


Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]
Weighted Sum :
 [[0.56]
 [0.4 ]
 [0.92]]
Output :
 [[0.63645254]
 [0.59868766]
 [0.71504211]]
Loss :
 [[0.04405559]
 [0.11947564]
 [0.027067  ]]


In [3]:
#Forward pass with hidden layer (matrix multiplication) 

In [4]:

def forwardpass(x,w1,w2,b1,b2):
  #input to hidden layer
  weighted_sum1=np.dot(x,w1)+b1
  print("Weighted Sum from input layer :\n",weighted_sum1)
  h_in=activation(weighted_sum1)
  #hidden to output layer
  weighted_sum2=np.dot(h_in,w2)+b2
  print("Weighted Sum from hidden layer :\n",weighted_sum2)
  h_out=activation(weighted_sum2)
  return h_out

#input data
x=np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

#targets
targets=np.array([[1], [0], [1]])

# Weights and biases for the input layer to hidden layer
w1= np.array([[0.8, 0.2], [0.4, 0.9]])
b1 = np.array([0.1, 0.5])

# Weights and bias for the hidden layer to output layer
w2 = np.array([[0.3], [0.7]])
b2= np.array([0.2])

final_output=forwardpass(x,w1,w2,b1,b2)
loss=loss_function(targets,final_output)

print("Input Data :\n",x)
print("Output :\n",final_output)
print("Loss :\n",loss)


Weighted Sum from input layer :
 [[0.62 0.87]
 [0.54 1.17]
 [1.1  1.47]]
Weighted Sum from hidden layer :
 [[0.88838755]
 [0.92374524]
 [0.9942182 ]]
Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]
Output :
 [[0.70855731]
 [0.71580461]
 [0.72992029]]
Loss :
 [[0.02831295]
 [0.17079208]
 [0.02431435]]


In [5]:
#Forward pass with matrix multiplication with Keras 

In [8]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def forward_pass(x, epochs=100):
    model = Sequential()
    model.add(Dense(units=1, activation='sigmoid', input_dim=2))  # Input to output
    model.compile(optimizer='adam', loss='mean_squared_error')
    model.fit(x, x, epochs=epochs)
    output = model.predict(x)
    return output

# Input data
x = np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

# Output data
output = forward_pass(x)

print("\nInput Data :\n", x)
print("\nOutput Data :\n", output)


Epoch 1/100
1/1 [==============================] - 0s 231ms/step - loss: 0.0826
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0825
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0823
Epoch 4/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0822
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0821
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0819
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0818
Epoch 8/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0817
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0815
Epoch 10/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0814
Epoch 11/100
1/1 [==============================] - 0s 19ms/step - loss: 0.0813
Epoch 12/100
1/1 [==============================] - 0s 11ms/step - loss: 0.0811
Epoch 13/100
1/1 [==============================] - 0s 10

In [6]:
#Forward passes with hidden layer (matrix multiplication) with Keras.

In [9]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def forward_pass(x, epochs=100):
    model = Sequential()
    model.add(Dense(units=2, activation='sigmoid', input_dim=2))  # Input to hidden
    model.add(Dense(units=1, activation='sigmoid'))  # Hidden to output
    model.compile(optimizer='adam', loss='mean_squared_error')
    model.fit(x, x, epochs=epochs)
    output = model.predict(x)
    return output

# Input data
x = np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

# Output data
output = forward_pass(x) 

print("\nInput Data :\n", x)
print("\nOutput Data :\n", output)


Epoch 1/100
1/1 [==============================] - 1s 1s/step - loss: 0.0694
Epoch 2/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0694
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0693
Epoch 4/100
1/1 [==============================] - 0s 10ms/step - loss: 0.0693
Epoch 5/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0692
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0692
Epoch 7/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0692
Epoch 8/100
1/1 [==============================] - 0s 9ms/step - loss: 0.0691
Epoch 9/100
1/1 [==============================] - 0s 15ms/step - loss: 0.0691
Epoch 10/100
1/1 [==============================] - 0s 15ms/step - loss: 0.0690
Epoch 11/100
1/1 [==============================] - 0s 11ms/step - loss: 0.0690
Epoch 12/100
1/1 [==============================] - 0s 8ms/step - loss: 0.0689
Epoch 13/100
1/1 [==============================] - 0s 9ms