# Name    : Abhishek Subhash Swami
# Roll No.:

# **Experiment No. 4**
# *Linear Algebra Tensors - Tensor Arithmetic ( Implementing matrix multiplication )*

## Linear Algebra Tensors


>**Definition:**
A tensor is a mathematical object that generalizes scalars, vectors, and matrices. It is a multi-dimensional array of elements, and its type is determined by the number of indices required to specify its components. Tensors can be thought of as a way to represent multi-dimensional data or transformations between vector spaces.

>**Order/Rank of a Tensor:**
The order (or rank) of a tensor refers to the number of indices required to specify its components. A scalar is considered a 0th-order tensor, a vector is a 1st-order tensor, a matrix is a 2nd-order tensor, and so on.

>**Components of a Tensor:**
The components of a tensor are the individual elements that make up the tensor. For example, a 2nd-order tensor (matrix) has components that can be indexed using two indices: ```A[i][j]```, where `i` represents the row index and `j` represents the column index.

>**Tensor Notation:**
Tensors are often represented using uppercase letters, and their components are denoted using lowercase letters with indices. The placement of indices is important. Upper indices are often associated with contravariant transformations, while lower indices are associated with covariant transformations.

>**Tensor Operations:**
Tensors can undergo various operations similar to matrices. These include addition, scalar multiplication, and contraction. Contraction involves summing over a paired upper and lower index. Tensors can also be multiplied together using tensor products or tensor contractions.

>**Tensor Product:**
The tensor product combines tensors to form a new tensor. For two tensors A and B, the tensor product `A ⊗ B` results in a new tensor with components ```(A ⊗ B)[i][j] = A[i] * B[j]```, where i and j are indices corresponding to the original tensors.

>**Tensor Contractions:**
A tensor contraction involves summing over one paired upper and lower index of a tensor. This operation can lead to the reduction of tensor rank. For example, contracting a 2nd-order tensor A with its transpose A^T along indices j and k yields a 0th-order tensor (scalar) by summing ```A[j][k] * A^T[k][j]```.

>**Tensor Spaces:**
Tensors can exist in various tensor spaces. A tensor space is characterized by its dimensionality, which is determined by the number of basis vectors along each index direction. Just as vectors span vector spaces and matrices span spaces of linear transformations, tensors span higher-order multi-dimensional spaces.

>**Applications of Tensors:**
Tensors find applications in a wide range of fields. In physics, they are used to represent physical quantities like stress, strain, and electromagnetic fields. In machine learning, they are fundamental for deep learning models and neural networks. Tensors also play a significant role in differential geometry, general relativity, and quantum mechanics.

>**Conclusion:**
Tensors are a powerful mathematical concept that extends the notions of scalars, vectors, and matrices to higher dimensions. They are essential for describing complex data structures and mathematical operations in various fields of science and engineering. Understanding tensors is crucial for advanced studies in linear algebra, physics, engineering, and computer science.

## Tensor Arithmetic
>Tensor arithmetic involves performing mathematical operations on tensors, which are multi-dimensional arrays. These operations include addition, scalar multiplication, element-wise multiplication, and more. Python libraries like NumPy and TensorFlow provide tools for performing tensor arithmetic efficiently.

In [ ]:





# Using Numpy

import numpy as np

# Create tensors (multi-dimensional arrays) using NumPy
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print('tensor_a\n',a)
print('tensor_b\n',b)

tensor_a
 [[1 2]
 [3 4]]
tensor_b
 [[5 6]
 [7 8]]


In [ ]:
# Addition
tensor_sum = a + b
print("Sum of tensors:\n",tensor_sum)

# Scalar multiplication
scalar = 2
tensor_scaled = scalar * a
print("\nScalar multiplication:\n",tensor_scaled)

# Element-wise multiplication
tensor_product = np.multiply(a,b) #a*b
print("\nElement-wise multiplication:\n",tensor_product)

#matrix multiplication
dot_product=a@b # equivalent to np.dot(a,b)
print("\nMatrix multiplication:\n",dot_product)

Sum of tensors:
 [[ 6  8]
 [10 12]]

Scalar multiplication:
 [[2 4]
 [6 8]]

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Matrix multiplication:
 [[19 22]
 [43 50]]


In [ ]:




# Using Tensorflow





import tensorflow as tf

# Create tensors using TensorFlow
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Addition
tensor_sum = tf.math.add(tensor_a, tensor_b)
print("Sum of tensors:\n",tensor_sum)

# Scalar multiplication
scalar = 2
tensor_scaled = tf.math.scalar_mul(scalar, tensor_a)
print("Scalar multiplication:\n",tensor_scaled)

# Element-wise multiplication
tensor_product = tf.math.multiply(tensor_a, tensor_b)
print("\nElement-wise multiplication:\n",tensor_product)

#dot product
dot_product = tf.linalg.matmul(tensor_a, tensor_b)
print("\nDot Product:\n",dot_product)



Sum of tensors:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Scalar multiplication:
 tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)

Element-wise multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)

Dot Product:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
