# Name : Abhishek Subhash Swami
# Roll No. : 13




# Experiment No. 6 : Implementation of forward pass

## Forward Pass
>The forward pass, often referred to as forward propagation, is a fundamental step in the operation of artificial neural networks. It's the process of moving input data through the network's layers to compute an output or prediction. The forward pass is a critical step in the network's operation and sets the stage for subsequent tasks like training and evaluation.

Here's how the forward pass works:

1. **Input Layer:** The process begins with the input layer, where the raw input data is fed into the network. Each node (neuron) in the input layer represents a feature or element of the input data.

2. **Weighted Sum and Activation:** The input data is multiplied by weights associated with the connections between neurons in adjacent layers. These weighted sums are calculated for each neuron in the subsequent layer. Additionally, a bias term might be added to the weighted sum. The weighted sum is then passed through an activation function to introduce non-linearity to the model. The result of the activation function is the output of the neuron.

3. **Propagation:** The output from the first layer becomes the input for the second layer. This process is repeated for each layer in the network, with the output of each layer being fed as input to the next layer.

4. **Output Layer:** The final layer in the network produces the output. Depending on the problem being solved, the output might represent class probabilities (in a classification problem) or numerical predictions (in a regression problem).

5. **Loss Computation:** The output is then compared to the target (ground truth) values using a loss function. The loss function quantifies the difference between the predicted output and the actual target values.

>In summary, the forward pass involves passing input data through the network layer by layer, computing weighted sums and applying activation functions at each layer, and finally producing an output. This output is then compared with the ground truth using a loss function to determine how well the network is performing.

>The forward pass sets the stage for training the neural network, during which the network's weights are adjusted to minimize the loss function, allowing it to make more accurate predictions over time.

### Forward Pass with Matrix Multiplication

In [ ]:
import numpy as np

def activation(z):
  return 1/(1+np.exp(-z))

def loss_function(target,output):                #Mean Squared Error
  return (1/len(target))*np.square(target-output)

def forwardpass(x,weights,bias):
  weighted_sum=np.dot(x,weights)+bias
  print("Weighted Sum :\n",weighted_sum)
  output=activation(weighted_sum)
  return output

#input data
x=np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

#weights
weights=np.array([[0.8], [0.2]])

#targets
targets=np.array([[1], [0], [1]])

#bias
bias=np.array([0.1])

print("Input Data :\n",x)

output=forwardpass(x,weights,bias)
loss=loss_function(targets,output)

print("Output :\n",output)
print("Loss :\n",loss)


Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]
Weighted Sum :
 [[0.56]
 [0.4 ]
 [0.92]]
Output :
 [[0.63645254]
 [0.59868766]
 [0.71504211]]
Loss :
 [[0.04405559]
 [0.11947564]
 [0.027067  ]]


### Forward Pass with Hidden Layer (Matrix Multiplication)

In [ ]:


def forwardpass(x,w1,w2,b1,b2):
  #input to hidden layer
  weighted_sum1=np.dot(x,w1)+b1
  print("Weighted Sum from input layer :\n",weighted_sum1)
  h_in=activation(weighted_sum1)
  #hidden to output layer
  weighted_sum2=np.dot(h_in,w2)+b2
  print("Weighted Sum from hidden layer :\n",weighted_sum2)
  h_out=activation(weighted_sum2)
  return h_out

#input data
x=np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

#targets
targets=np.array([[1], [0], [1]])

# Weights and biases for the input layer to hidden layer
w1= np.array([[0.8, 0.2], [0.4, 0.9]])
b1 = np.array([0.1, 0.5])

# Weights and bias for the hidden layer to output layer
w2 = np.array([[0.3], [0.7]])
b2= np.array([0.2])

final_output=forwardpass(x,w1,w2,b1,b2)
loss=loss_function(targets,final_output)

print("Input Data :\n",x)
print("Output :\n",final_output)
print("Loss :\n",loss)


Weighted Sum from input layer :
 [[0.62 0.87]
 [0.54 1.17]
 [1.1  1.47]]
Weighted Sum from hidden layer :
 [[0.88838755]
 [0.92374524]
 [0.9942182 ]]
Input Data :
 [[0.5 0.3]
 [0.2 0.7]
 [0.8 0.9]]
Output :
 [[0.70855731]
 [0.71580461]
 [0.72992029]]
Loss :
 [[0.02831295]
 [0.17079208]
 [0.02431435]]


###Forward pass without hidden layer (matrix multiplication) with Keras

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def forward_pass(x, epochs=100):
    model = Sequential()
    model.add(Dense(units=1, activation='sigmoid', input_dim=2))  # Input to output
    model.compile(optimizer='adam', loss='mean_squared_error')
    model.fit(x, x, epochs=epochs)
    output = model.predict(x)
    return output

# Input data
x = np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

# Output data
output = forward_pass(x, epochs=10000)

print("\nInput Data :\n", x)
print("\nOutput Data :\n", output)


Streaming output truncated to the last 5000 lines.
Epoch 3989/10000
1/1 [==============================] - 0s 14ms/step - loss: 0.0253
Epoch 3990/10000
1/1 [==============================] - 0s 15ms/step - loss: 0.0253
Epoch 3991/10000
1/1 [==============================] - 0s 17ms/step - loss: 0.0253
Epoch 3992/10000
1/1 [==============================] - 0s 19ms/step - loss: 0.0253
Epoch 3993/10000
1/1 [==============================] - 0s 17ms/step - loss: 0.0253
Epoch 3994/10000
1/1 [==============================] - 0s 9ms/step - loss: 0.0253
Epoch 3995/10000
1/1 [==============================] - 0s 10ms/step - loss: 0.0253
Epoch 3996/10000
1/1 [==============================] - 0s 9ms/step - loss: 0.0253
Epoch 3997/10000
1/1 [==============================] - 0s 9ms/step - loss: 0.0253
Epoch 3998/10000
1/1 [==============================] - 0s 10ms/step - loss: 0.0253
Epoch 3999/10000
1/1 [==============================] - 0s 10ms/step - loss: 0.0253
Epoch 4000/10000
1/1 [======

### Forward pass with hidden layer (matrix multiplication) with Keras

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def forward_pass(x, epochs=100):
    model = Sequential()
    model.add(Dense(units=2, activation='sigmoid', input_dim=2))  # Input to hidden
    model.add(Dense(units=1, activation='sigmoid'))  # Hidden to output
    model.compile(optimizer='adam', loss='mean_squared_error')
    model.fit(x, x, epochs=epochs)
    output = model.predict(x)
    return output

# Input data
x = np.array([[0.5, 0.3], [0.2, 0.7], [0.8, 0.9]])

# Output data
output = forward_pass(x, epochs=10000)  # Specify the number of epochs

print("\nInput Data :\n", x)
print("\nOutput Data :\n", output)


Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 14ms/step - loss: 0.0258
Epoch 3709/10000
1/1 [==============================] - 0s 8ms/step - loss: 0.0258
Epoch 3710/10000
1/1 [==============================] - 0s 8ms/step - loss: 0.0258
Epoch 3711/10000
1/1 [==============================] - 0s 12ms/step - loss: 0.0258
Epoch 3712/10000
1/1 [==============================] - 0s 14ms/step - loss: 0.0258
Epoch 3713/10000
1/1 [==============================] - 0s 13ms/step - loss: 0.0258
Epoch 3714/10000
1/1 [==============================] - 0s 12ms/step - loss: 0.0258
Epoch 3715/10000
1/1 [==============================] - 0s 11ms/step - loss: 0.0258
Epoch 3716/10000
1/1 [==============================] - 0s 9ms/step - loss: 0.0258
Epoch 3717/10000
1/1 [==============================] - 0s 13ms/step - loss: 0.0258
Epoch 3718/10000
1/1 [==============================] - 0s 11ms/step - loss: 0.0258
Epoch 3719/10000
1/1 [=======================