# Name    : Abhishek Subhash Swami
# Roll No.:

# **Experiment No. 2**
# *Data Manipulation (numpy library) operations broadcasting indexing and slicing*

## Data Manipulation
> It is a crucial aspect of working with data in various fields. The numpy library is a powerful tool in Python that enables efficient data manipulation through its array structures. It offers various operations, including broadcasting, indexing, and slicing.

### Broadcasting
> Numpy's broadcasting allows you to perform operations on arrays of different shapes without explicitly creating loops. When operating on arrays with different shapes, numpy automatically broadcasts the smaller array to match the shape of the larger array. This simplifies calculations and enhances code efficiency.

In [1]:
import numpy as np

#create a numpy array
arr1=np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [2]:
b=5
result=arr1*b
print(result)

[ 5 10 15 20 25 30 35 40 45]


### Indexing
> Numpy arrays can be indexed in multiple ways. You can use integers, slices, or boolean arrays to extract specific elements or subsets of elements from an array. For example, array[2] would retrieve the third element, and array[1:4] would extract elements from the second to fourth positions.

In [3]:
arr2 = np.array([10, 20, 30, 40, 50])

element = arr2[2]  # Accessing the third element
print(element)

30


In [4]:
subset = arr2[1:4]  # Extracting elements from index 1 to 3
print(subset)

[20 30 40]


### Slicing
> Slicing refers to extracting a portion of an array. It's done using the colon operator (:). For instance, array[2:5] would return elements from the third to fifth positions. Slicing can also be performed on multi-dimensional arrays to extract specific rows, columns, or submatrices.

In [5]:
# Slicing example
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

row_slice = matrix[1, :]  # Extracting the second row
print(row_slice)

[4 5 6]


In [6]:
column_slice = matrix[:, 1]  # Extracting the second column
print(column_slice)

[2 5 8]


In [7]:
submatrix = matrix[0:2, 1:]  # Extracting a submatrix from rows 1 and 2, and columns 2 and 3
print(submatrix)

[[2 3]
 [5 6]]
